Repository AbdelrahmanBadwy/Lawyer_Assistant_App, pull requests merged in 2023-12, with the labels that each got.

#9 frontend/feat/#8/conversation_chat_classes: Adding Classes Chat And C…
  LAA/LAA.pro
  LAA/LAA.pro.user
  LAA/chat.cpp
  LAA/chat.h
  LAA/conversation.cpp
  LAA/conversation.h
Labels: 1h

#13 general-feat-10-request_message_to_server
  LAA/LAA.pro
  LAA/LAA.pro.user
  LAA/mainwindow.cpp
  LAA/mainwindow.h
  LAA/mainwindow.ui
Labels: enhancement, 4 h, Qt, integration

#17 general-feat-#10-View_Threads_From_Database
  LAA/LAA.pro.user
  LAA/mainwindow.cpp
  LAA/mainwindow.h
Labels: 4 h, 2 h

#22 Frontend-bug-#19-display_specific_characters
  LAA/mainwindow.cpp
Labels: bug, 1h, frontend

#28 general-feat-27-newThread_button
  LAA/LAA.pro.user
  LAA/mainwindow.cpp
  LAA/mainwindow.h
  LAA/mainwindow.ui
Labels: 2 h

#29 General-feat-14-view_chats_from_db
  LAA/conversation.cpp
  LAA/conversation.h
  LAA/mainwindow.cpp
  LAA/mainwindow.h
  LAA/mainwindow.ui
Labels: enhancement, 4 h, Qt, database, integration, openAi, frontend

#31 General-feat-#3-chat_page
  .gitignore
  LAA/LAA.pro
  LAA/LAA.pro.user
  LAA/chat.cpp
  LAA/chat.h
  LAA/chatbutton.ui
  LAA/conversation.cpp
  LAA/conversation.h
  LAA/main.cpp
  LAA/mainwindow.cpp
  LAA/mainwindow.h
  LAA/mainwindow.ui
  LAA/threadbutton.ui
Labels: enhancement, Qt, database, structure, frontend, 30h

#32 backend-feat-20-adding_function_calling_to_assistant
  Backend/app.js
  Backend/package-lock.json
  Backend/package.json
  Backend/saLaw.txt
Labels: enhancement, backend, database, openAi, 25h, initial_integration

#34 backend-bug-33-deadline_invalid_date_format
  Backend/app.js
Labels: bug, enhancement, help wanted, 4 h, backend, database

#36 frontend-feat-25-authentication_page_api
  LawyerAssistantApp.pro
  LawyerAssistantApp.pro.user
  assigntodo.cpp
  assigntodo.h
  authenticationPageApi.cpp
  authenticationpageapi.h
  boardwindowapi.cpp
  boardwindowapi.h
  loginandsignupdialog.cpp
  loginandsignupdialog.h
  loginandsignupdialog.ui
  main.cpp
  toDo.cpp
  toDo.h
  todoboardwindow.h
  todocomponent.cpp
  todocomponent.h
  todosboardwindow.cpp
  todosboardwindow.h
  user.cpp
  user.h
Labels: 4 h, integration
